### ISSUE TITLE
pitching moment due to pitch rate

### ISSUE THREAD

**Issue by kvnjonathan70** [NikolaiVChr/f16#202]
Would you mind clearing a doubt ? if would be really kind of you.

while talking about properties, say pitch rate q, it changes dynamically while flying, if we want to obtain 10 coefficient values of pitching moment due to pitch rate with respect to alpha like the one from f16 by you where you used wind tunnel data, how can it be obtained from cfd, or do we really need it if we are making 3d table for alpha, beta, and control surface deflection ? in the formula, velocities/q-rad-sec is dynamic value and coefficient is also unknown. i am trying to get aerodynamic data through cfd and put it in jsbsim for simulation.

**Comment by NikolaiVChr** [comment]
No, you can make a decent FDM without derivatives such as pitch due to pitch rate.
But if you got data for it, it will of course add to the fidelity of the model to have it.

**Comment by kvnjonathan70** [comment]
Thanks for the reply, really appreciate.

I went through this paper (link below), they have computationally calculated aerodynamics coefficient without any rate term, i see that the angular rates were not that satisfying compared to real values.
https://www.intechopen.com/online-first/development-of-the-flight-dynamic-model-fdm-using-computational-fluid-dynamic-cfd-simulations-for-an

We are at initial stage and would really like to add angular rates to jsbsim FDM, do you think if there is any procedure to compute coefficient of pitching moment due to pitch rate at different AOA ?
what are the possibilities, would you mind please suggesting ?

**Comment by NikolaiVChr** [comment]
I do not know how to calculate it.

But I do know intuitively why its there and what it does.
It can be thought of as drag due to spinning through the air. Which is also why it works as a damping effect on pitch rate. The faster the aircraft pitch rate is, the more 'drag' it will encounter for example the horizontal tail in particular, as the htail hit lots of air molecules, the bigger pitch rate, the more drag. That drag will produce a pitch moment opposite direction of the rotation, hence the damping factor.

Hope that helps.

**Comment by kvnjonathan70** [comment]
Thanks man, its was helpful, meanwhile i came across a paper where they obtained angular rates through CFD.
