### ISSUE TITLE
Fuel System

### ISSUE THREAD

**Issue by legoboyvdlp** [NikolaiVChr/f16#229]
Improvements:
- [x] Fuel master switch - shuts off fuel to engine. Probability to extinguish fire. 
- [ ] Gravity feed with OFF
- [ ] Less chance of fire with inerting set to on
- [x] Air refuel depressurizes external tanks so feed stops. 
- [x] External tanks require ECS pressure to feed, and AIR SOURCE not in RAM or OFF
- [x] Centerline feeds first to wing tanks, then wing tanks UNLESS wing tank first switch is set
- [x] Engine is fed from the forward / aft reservoirs to engines
- [x] Fuel feeds external --> wing --> fuselage --> reservoir 
- [x] CFTS -- gravity feed to internal wing tanks 
- [ ] Animations for INERTING / WING TANK FIRST switches
- [x] Forward CG helper: if FUEL QTY SEL in NORM and total fuselage less than 2800 lb, fuel is fed from aft to front to maintain between 300 and 450lb nose heavy.  Powered by emergency DC BUS 2.

**Comment by ph-jake** [comment]
Currently the JSBSIM model is setup to directly connect the available tanks to the simulation, which uses them based on priority. (Most of) these items require the introduction of a Fuel Transfer layer between the tanks and the simulation engine feed to contain the logic to simulate these fuel transfers before they enter the engine.
Most of the items need detail added before a Fuel Transfer layer design can be made.

**Comment by NikolaiVChr** [comment]
The reason I didn't make a full fledged fuel system (ala what Viggen has) is that the F-16 is extremely sensitive to weight distributions having the CoG 4% MAC behind the Aerodynamic Reference Point. (Standard for 3rd gen. aircraft is about 5% in-front)

Also much of it would be guess work as the manuals don't have so much details about it.

So however you drain them, make sure the CoG don't move much backwards.

**Comment by ph-jake** [comment]
Good point. The last bullet item in the list suggested something in that line. Indeed we need more details and/or model the weight distribution (maybe even including stores?) for this to work.

**Comment by NikolaiVChr** [comment]
Status December 2021:

Engine
* [ ] Engine feeds only from reservoirs
* [ ] Engine feeds determined by ENG FEED knob
* [x] FUEL MASTER is last step passed before reaching engine (JSF not affacted by fuel master)
* [ ] ENG FEED AFT: feeds from AFT reservoir and pumps fuel to FWD tanks. CoG moves FWD.
* [ ] ENG FEED FWD: feeds from FWD reservoir and pumps fuel to AFT tanks. CoG moves AFT.

Transfer system
* [ ] FWD and AFT to FWD and AFT reservoirs.
* [x] **Auto fwd fuel transfer system**: If FUEL QTY SEL in NORM and total fuselage is less than 2800: When FWD 300 lbm less than AFT then its transfers so that FWD has 450 LBM more than AFT.

Ext Tanks
* [ ] EXT FUEL TRANS : WING FIRST: outer droptanks emptied before center droptank, else opposite.
* [ ] EXT FUEL TRANS : NORM: center droptank to both internal wing tanks. After it empties, ext wing tanks feed to their respective internal wing tank.
* [ ] AIR SOURCE must be in NORM or DUMP for fuel to transfer from droptanks to wingtanks. And AIR REFUEL switch must not be in OPEN.

**Comment by NikolaiVChr** [comment]
![image](https://user-images.githubusercontent.com/3764194/147773189-743e9447-6d44-40d8-9a9a-769afc649417.png)
