### ISSUE TITLE
WIP: Comments on commits summer 2020

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#264]
Since I have not looked at the aircraft for 4 month, I have some catching up to do. I didn't want to open 30 issues so this is a collection of commit notes, feel free to comment on them.
Last 2 months not looked at yet (except for a couple of commits)

General things to do
- Remove all new nasal canvas property fetches of color from inside code segments and collect them at the the top in variables.
- The fuel system increases the static margin and messes with handling of the aircraft.
- Find out why dragchute is again tied to livery. IMO it's confusing to pilots, never knowing if they are flying with chute or not, remembering a block is simple.
- Verify that @ph-jake is listed in author file.
- Figure out the order of the authors. It used to be ordered timewise for when people had worked on it. Seems to be random now.

1bd30e8ca89b1841ac4931fd325320f061dc301d

1. Do not move the switch
2. Do not put a new listener each time refuel door is opened
3. Do this for the switch also, not only the keybind

00ad71a63111073b3266d09c5919e47b54cc740b

I don't see this change in F15! Or the automats etc. etc.
Revert..

72bc56577310677b5ed58ce891c0418770f402b7

details?

5c9e85ae05c8114899628f5c63f6a54d11a8f9cd

Did what to the Ambient Occlusion map?

a318f22a9dbc2af2fc3a3d02e264b9612f48b9fa

Check

b6c06a46520da7f088dfc75f9900cb0b2dc43cd6

Why change Josh name?

367be6785abd285140add540e96052106289228a

Modify to seaskimming

e3181faed3ece143469eca31cdf2e67bdc386d25

Revert

7c37cd477672322d22cdb84d7c755b076eac2eb3

f16.nas weird programming

d17d1e7b24db22c9230d1b88b58e0a58121c1cf7

Only half done, and check that Bore cross is still in HUD and not too high up.

**Comment by JMaverick16** [comment]
> Remove all new nasal canvas property fetches of color...
I don't know yet how to do that, I'm fine as long as it keeps the current settings for Blocks.

> Find out why dragchute is again tied to livery. IMO it's confusing to pilots, never knowing if they are flying with chute or not, remembering a block is simple.
It was done on purpose, dragchute must be specific to the spec of the airforce it's using. I won't give up realism because someone is confused.

Jake will be included in the list soon. Author list in set files was sorted in order of relevance instead of time-frame. I prefer it, although might not be a big deal so better discussing it.

> Do not move the switch
> Do not...
Method was suggested by legoboy but I noticed as well the light switch is not flicking on the first attempt. Will need to be reviewed. (PS: I'm still learning nasal).

> I don't see this change in F15! Or the automats etc. etc. Revert..
No, not my fault if people don't push changes to their planes timely. Adjustments were due because several values were off and new data was found. As per Pinto, F-15 is not so much compliant to OPRF requirements anymore unless updated (reminds me I should push the latest to the Mirage at least).

> details?
I was tired and got sidetracked after doing it so forgot. Basically it's payload options optimization (which I will have to redo again in light of the new ways of conducting event being done by OPRF admins).

> Why change Josh name?
He asked for it to be so, like in all his other projects.

> Revert e3181fa
No, after commenting out I realized it broke the loads so had to set it back as it was.

> f16.nas weird programming
Yep, it was restored back after discussing about Python 4.

> Only half done...
That's above my paygrade.

**Comment by Rudolf339** [comment]
Re: RCS changes...

Shouldn't all aircraft be synced with https://github.com/NikolaiVChr/OpRedFlag/blob/master/Damage/damage.nas and not the f-16?

Also, I find it strange that the Su-27/J-11A is 15 and the Su-34 is 8 and marked "should be less". It's the same basic airframe and to my knowledge doesn't have radar absorbing coating so it should be about the same, no?

**Comment by JMaverick16** [comment]
RCS values are not listed in the damage file, they are their own rcs.nas which pretty much became the standard since it got the most active revisions. I agree though that should be stored in the OPRF repo so people can retrieve it from there instead of digging elsewhere, reason why I also added a `#REVISION ` tag above the lists to know if it's up to date or not.

Regarding Su-27 and -34 I found contrasting values, some stating it's pretty much the same as Su-27 (which 15 is a good match) and others saying it's about 1 sqmt or so, which I don't trust fully. I think settling for a middle way is the best. The sad part about RCS values is that even published ones might not be actual, leaving aside all the complications that load and such bring.

**Comment by Rudolf339** [comment]
I edited after posting but github hook doesn't show that.

**Comment by NikolaiVChr** [comment]
Well, then must tell the pilot after he has switched livery if he has a dragchute or not, people shouldn't have to go into exterior view to verify if they are able to brake by chute or not.

> No, not my fault if people don't push changes to their planes timely.

I have got no messages about RCS needed to be changed in Automats for example. So I think this one is on you.

> I was tired and got sidetracked after doing it so forgot.

So who is that person you added to the author list?

**Comment by NikolaiVChr** [comment]
I found out what you did to the Ambient Occlusion image, you reduced the shadow of the link16 antennae on the front.

**Comment by JMaverick16** [comment]
> Well, then must tell the pilot after he has switched livery if he has a dragchute or not, people shouldn't have to go into exterior view to verify if they are able to brake by chute or not.
Yeah could be done someway.

> I have got no messages about RCS needed to be changed in Automats for example. So I think this one is on you.

¯\_(ツ)_/¯ We're always in time to fix it, as long as it includes all values, and not only OPRF ones (yes, I wanna use the F-35 vs automats and see if I can sneak past them).

> So who is that person you added to the author list?

From the website where all the cockpit panels come from https://www.xflight.de/pe_org_doc.htm, both Martin "Pegasus" Schmitt (listed in F-16 main authors) and Prohm “Rama” Snitwong are authors of those files. Thought it was legit to add him as well for recognition.

> I found out what you did to the Ambient Occlusion image, you reduced the shadow of the link16 antennae on the front.

Ah yeah that. The non-link 16 variants looked terribly bad with the shadow applied to them, so reduced to almost zero that shadow.

**Comment by NikolaiVChr** [comment]
> * Remove all new nasal canvas property fetches of color from inside code segments and collect them at the the top in variables.

Done for MFDs.

> * The fuel system increases the static margin and messes with handling of the aircraft.

In progress.

> * Verify that @ph-jake is listed in author file.

He is now.

> [1bd30e8](https://github.com/NikolaiVChr/f16/commit/1bd30e8ca89b1841ac4931fd325320f061dc301d)

Fixed.

> [d17d1e7](https://github.com/NikolaiVChr/f16/commit/d17d1e7b24db22c9230d1b88b58e0a58121c1cf7)

Fixed.

**Comment by JMaverick16** [comment]
I assume this is completed by now right?
