### ISSUE TITLE
Missing/Broken shaders/broken texture spamming and crashing mp users.

### ISSUE THREAD

**Issue by Megaf** [NikolaiVChr/f16#342]
Whenever there's an MP F-16 nearby the following message spams in the log of MP users causing all sorts of bad effects.
```
 1146.23 [ALRT]:input      Could not locate shaderShaders/ubershader-gbuffer.frag
 1146.23 [ALRT]:input      Error building technique: couldn't find shader Shaders/ubershader-gbuffer.frag
 1146.24 [INFO]:io         From effects transparent /home/reglnx/FlightGear-Next/aircraft/f16/Models/Effects/fuselage/dirt.png will generate mipmap only
 1146.28 [INFO]:io         From effects transparent /home/reglnx/FlightGear-Next/aircraft/f16/Models/Effects/fuselage/ao.png will generate mipmap only
 1146.88 [INFO]:io         From effects transparent /home/reglnx/FlightGear-Next/aircraft/f16/Models/Effects/fuselage/rust1.png will generate mipmap only
```

The message will continue to get spammed until FG is closed/crashed no matter if the F-16 is gone or not.

### Some of the negative effects are.

- Scenery stops loading, making landing a little more challenging since there will be only void to be seen.
- Closing FlightGear will be impossible since it freezes on closing.
- The error quickly fills the log file with several dozens of MB, could even cause the disk to run out of space.
- If FG was ran from the console, the system might run out of RAM because the console will fill the RAM with error messages.
- Degraded FPS.

### Attached log from MP user (me)
https://gist.github.com/Megaf/cabc683f815455f2f3e80d1ad79b6090

**Comment by Megaf** [comment]
@legoboyvdlp It's not _my_ problem, it's everyone's in the MP problem.

**Comment by legoboyvdlp** [comment]
That is false. It only affects those who choose to use -next, therefore clearly not "everyone", but rather a small minority of users, all of whom are expected to be aware of what they are doing and what they need to do to accommodate for using a rapidly-changing version.

You have several options:

1. Use 2020.3.5 per the current recommendations
2. Use the compositor2 branch for your local f16 aircraft, as you should be if you choose to ignore 1)

To make an error report because of using a incompatible version is very misleading.

As it happens there appears to be a regression in -next that the shader references no longer look in the aircraft directory -- I've just fixed that by specifying a direct path in https://github.com/NikolaiVChr/f16/commit/85e67cccc18a67ae00e8a67941b989a50ebe0e1b

May I also direct you to https://github.com/NikolaiVChr/f16/commit/40ffbeded803062f8d6fced21cb15cb85c933cfe and to the compositor2 branch: https://github.com/NikolaiVChr/f16/tree/compositor2

**Comment by Megaf** [comment]
And how am I supposed to know that I should be using another branch? master is the default branch on this repository.
Don't blame the user for your fault or the application fault.

And this error had been happening for months now. I had already commented with another user and they had commented with F-16 devs about it and nothing was done. Hence, me opening this issue now.

Anyway, thank you for the information and PR.

**Comment by JMaverick16** [comment]
_And how am I supposed to know that I should be using another branch?_

Maybe by doing some research first, instead of opening issues without an accurate verification. Current LTS is 2020.3.6, that's where the master branch works as stated in the README file. If you want to use a different version of FG, especially next, verify that the planes you intend to use work with said version first. That's all that has to be said about this.
