### ISSUE TITLE
At touchdown the nose pitch up

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#463]
https://discord.com/channels/379782363061813248/761204876038242325/943949875572248586

**Comment by LJQCN101** [comment]
My two cents: It looks like an aerodynamic issue of Cm curve for 0.6 mach (NASA TP-1538) still being used in ground effect, hence the pitch instability.
![Cm](https://user-images.githubusercontent.com/14259702/175228126-7500d5c4-35d4-4918-8db0-59bd06ccf61f.jpg)


The FLCS also contributes to this by:
1. AOA feedback sets to zero upon MLG WOW. Which means the pitch-down command above 10 degrees AOA, and the static stability gain schedule on AOA, is no more.
![AOA feedback nulls](https://user-images.githubusercontent.com/14259702/175228185-55852f96-328c-47bd-bc49-17f012f11624.jpg)

2. LEF deflects -2 degrees upon MLG WOW, which can create a pitch-up moment.

**Comment by LJQCN101** [comment]
A real solution would be creating a Cm table for ground effect and take-off & landing roll. But that would not be easy finding the right coefficients.

A workaround solution is to modify the FLCS control logic to compensate for that instability. For example, change the logic switches that are based on MLG WOW to NLG WOW, so that the AOA feedback above 10 degrees and the static stability gain schedule can be utilised. (Or more importantly, the pitch integrator can be utilised to null the pitch-rate.)

**Comment by NikolaiVChr** [comment]
> change the logic switches that are based on MLG WOW to NLG WOW

Hmm, that is perhaps a real good idea.

**Comment by NikolaiVChr** [comment]
I had forgotten you suggested that. Came to the same idea last night, due to Josh finding out that not stopping the AoA paths fixed the issue plus Reaper suggesting that there was a switch with NLG that maybe should be MLG (that was not used in control though).

The only thing I did was change the switch for AOA from MLG to NLG.

Anyway, is committed with 146b05fc6f986c9eea415e7a148477b6c44d0c49 (the commit refers issue 170, should have been this issue). And it does indeed fix it (at least its much less), even without integrator help.
