### ISSUE TITLE
Arms: Add AIM-9X

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#468]
Someday... Just to piss off Rudolf

**Comment by NikolaiVChr** [comment]
Pull request #530 is related to this issue.

It is kinda on purpose the AIM-9X has not been added to the aircraft yet.

We have been trying to keep the aircraft weapons (especially A/A) to a max 1996/98 standard, due to the fact that we use it to fly missions with and against OPRF aircraft from that era or earlier.

But, I will help, with the condition that it get introduced only to the block 60.

You need to be able to look with HMCS over the shoulder and fire it.
So `<FCS-field-deg type="int">360</FCS-field-deg>`

Once its fired, it wont be able to see target but it will be able to turn towards it till it sees it, as it has been told where the target is. So `<guidance type="string">inertial</guidance>`, see below for midflight function that switches it to heat.

In station_manager.nas it should have a midflight function, so it uses pure pursuit for extreme turning until target is in front, then switch to normal Proportional Navigation:
```javascript
} elsif (me.weaponName == "AIM-9X") {
            mf = func (struct) {
              if (struct.deviation_deg != nil) {
                  if (struct.deviation_deg > 70) {
                    return {"navigation":"direct"};
                  } elsif (struct.deviation_deg < 70) {
                    return {"navigation":"OPN", "guidance":"heat"};
                  } elsif (struct.deviation_deg < 55) {
                    return {"navigation":"OPN", "guidance":"heat", "abort_midflight_function":1};
                  }
              }
              return {};
            };
```

Be aware that struct.deviation is angle from missile bore.

Please also note that `<seeker-field-deg>` is diameter, not radius, so the 90 probably have to be changed to 120.

Angular speed needs to be much higher for such a modern seekerhead, I recommend:
`<seeker-angular-speed-dps type="double">60</seeker-angular-speed-dps>`

**Comment by NikolaiVChr** [comment]
I also suggest this:

`<seeker-filter type="double">1.10</seeker-filter>`

**Comment by NikolaiVChr** [comment]
And this should probably be a bit lower than 0.8:
`<min-speed-for-guiding-mach>`
Otherwise after a narrow turn it might not guide again, the 0.8 is authentic for older sidewinders though.


And although probably more sensitive than the mike, its probably better at not locking at sun. So maybe a lower value for this than 7.5:
`<lock-on-sun-deg>`

**Comment by SP-NTX** [comment]
> But, I will help, with the condition that it get introduced only to the block 60.
This is most stupid thing i read today... 9X was in more blocks than 60.... and it SHOULD be added to keep this realistic, even if you loose fun from fighting in OPRF

**Comment by NikolaiVChr** [comment]
> This is most stupid thing i read today... 9X was in more blocks than 60....

Did you read the reason? We try to keep the aircraft to a certain year, which was before AIM-9X got introduced.

Anyway, its probably going to be introduced anyway, but we keep it out of main events.

**Comment by SP-NTX** [comment]
So we are magically stopping time in one part of history? I would like to do that... IRL...

**Comment by jakkos98** [comment]
What about, adding for example Block 52+, which will have those newer equipment/armaments, but without CDU from Block 60?

**Comment by NikolaiVChr** [comment]
I have added aim-9x to damage in our shared repo so it will trickle into the other aircraft.
Its now in automats too.
Please also note that I edited and expanded the comment in this thread a few replies back. The one with suggestions.
@BobDotCom

**Comment by NikolaiVChr** [comment]
> What about, adding for example Block 52+, which will have those newer equipment/armaments, but without CDU from Block 60?

We already have so many blocks to maintain, and are considering to make a b15 also. Not sure we need more.

**Comment by JMaverick16** [comment]
Also worth noting 52+ is simply an upgrade to the existing Block for certain air forces, not an actual brand new Block, so if ever, it might just get some of the features we can replicate into the existing version.

**Comment by SP-NTX** [comment]
this is starting to get more stupid and not the right way every single next message here

**Comment by JMaverick16** [comment]
You can ask yourself why...

**Comment by SP-NTX** [comment]
so do you

**Comment by SammySkycrafts** [comment]
> I don't know if you have tuned the drag-coeff yet. Else I recommend you make sure that at 25k ft co-altitude head2head with closing speed of M2.0 that it can hit non-manouvering target 15 nm out. Then it is in the DLZ/max-range envelope you have made.

Testing shows a good hit with the scenario described above with the current drag coeff in @BobDotCom's version which I calculated for him.

**Comment by BobDotCom** [comment]
This can be closed :)
