### ISSUE TITLE
2018.3 Fuel and Payload dialog changes

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#48]
The new fuel dialog will break the F16 payload system.

In future: set opt/lbs to non nil also for jsbsim in F16 payload system.
Also make use of setprop("sim/gui/dialogs/payload-reload",1); to reload the dialog.

**Comment by Zaretto** [comment]
As I possibly broke this - is it something that I need to fix in FGData

**Comment by NikolaiVChr** [comment]
Maybe not. I havent looked deep into it, but I think it can be fixed with changing 1 line in the f16.

Would like to know what payload-reload can do. Can I use it to repopulate the dialog especially the fuel tanks?

**Comment by Zaretto** [comment]
set sim/gui/dialogs/payload-reload to make the system payload dialog reload itself, for example if stores have been altered. 

All of this code was originally added because the F-15 has two dialogs that allow the external stores to be configured and this property is how the two can be kept in sync.

e.g if you add external tanks set sim/gui/dialogs/payload-reload and the system dialog should update.

**Comment by NikolaiVChr** [comment]
fixed
