### ISSUE TITLE
Radio compatibility

### ISSUE THREAD

**Issue by BobDotCom** [NikolaiVChr/f16#549]
The radio system is currently not compatible with FGCom-Mumble or Red Griffin ATC.

See: https://discord.com/channels/379782363061813248/761204876038242325/1105166742109565008

**Comment by NikolaiVChr** [comment]
Posted by Sammy:
FGCom-mumble marks the radios as unusable (I believe) due to the fact the property instrumentation/comm[x]/operable is missing. Setting this manually in the -set unfortunately doesnt seem to work as something seemingly is overriding it to false, any attempt with prop browser to change this fails and it stays as false

From the fg plugin documentation the following props are needed:


    COM radios:
```
        /instrumentation/comm[n]/operable
        /instrumentation/comm[n]/volume
        /instrumentation/comm[n]/frequencies/selected-mhz
        /instrumentation/comm[n]/ptt
        /instrumentation/comm[n]/cutoff-signal-quality
        /instrumentation/comm[n]/frequencies/selected-channel-width-khz
        /instrumentation/comm[n]/tx-power (nonstandard and optional; introduced by FGCom-mumble)
```

    ADF radios (local only, they can't transmit):
```
        /instrumentation/adf[n]/operable
        /instrumentation/adf[n]/volume-norm
        /instrumentation/adf[n]/frequencies/selected-khz
        /instrumentation/adf[n]/indicated-bearing-deg (read/write)
        /instrumentation/adf[n]/ident-audible
        /instrumentation/adf[n]/mode
```
[1:33 AM]SammySkycrafts: Red Griffin seems to use similar so enabling compatibility with FGCom-mumble could also enable it for RG

There are a few extra it says it needs however i suspect it may work without some of the more interesting ones, such as name and airport id:

```
/instrumentation/comm[x]/power-btn
/instrumentation/comm[x]/airport-id
/instrumentation/comm[x]/station-name
/instrumentation/comm[x]/track-distance-m
/instrumentation/comm[x]/true-bearing-to-deg
/instrumentation/comm[x]/volume-selected
```

**Comment by SammySkycrafts** [comment]
FGCom-mumble tested and working. Can be closed.
