### ISSUE TITLE
Sound: Low speed warning tone plays when flying at high speed but pulling high Gs/AoA

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#570]
The most common example is doing BFM (or any kind of hard maneuvering) and pulling hard on the stick at around 350/450+ kts it starts playing for literally minutes until stopping to maneuver.
It has been happening for years already, but I believe there's something wrong with it happening consistently at high speeds since it should on paper denote stalling instead.

**Comment by NikolaiVChr** [comment]
What does the tone sound like?
Your CAT setting?

**Comment by JMaverick16** [comment]
Nope, regular steady 250hz one.

**Comment by NikolaiVChr** [comment]
Your commit 63d3009 is not related to this, right? Because that's not a steady tone you reduced volume on.

I don't maneuver like you do, so can you check by deleting the tones 1 by 1 find out which tone we are talking about?
You can do the deleting in-flight, just Reload Aircraft Model after each delete, then the new sound xml takes effect.

**Comment by JMaverick16** [comment]
That commit was unrelated yes. Aimed at making it less annoying.

I've tested it as I was correcting the sounds earlier, and it's indeed the 250hz steady tone that screams, also happened with clean jet.

**Comment by NikolaiVChr** [comment]
96d407a67df863a10478ff95351f5471e44187dc simplified the calculation, has perhaps fixed the issue.

**Comment by JMaverick16** [comment]
Will try again this evening then, thx
